language: php
php:
  - 5.6
install:
  - composer install
before_script:
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
script:
  - vendor/bin/sculpin generate
after_success:
  - vendor/bin/sculpin publish --env=prod